stages:
  - test
  - build
  - publish

test:
  stage: test
  coverage: '/\d+\%\s*$/'
  script:
    - make check

build:
  stage: build
  only:
    - tags
  script:
    - make load VERSION=$CI_COMMIT_TAG
    - make build VERSION=$CI_COMMIT_TAG
    - make dist VERSION=$CI_COMMIT_TAG
    - make save VERSION=$CI_COMMIT_TAG # aws s3

pages:
  script:
    - make docs
  artifacts:
    paths:
      - public
  only:
    - master

publish:
  stage: publish
  only:
    - tags
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
      registry.neoway.com.br
    - make publish VERSION=$CI_COMMIT_TAG # docker

after_script:
  - make clean-ci
